/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java.neovim.demo;

import lombok.Getter;

public class App {

    @Getter
    private String test = "test";

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
